version: "3"

services:
  api:
    container_name: api
    build: server/
    ports:
      - 8000:8000
    volumes:
      - ./server:/app/server
      #- /usr/src/app/node_modules
    environment:
      - PORT=8000
    depends_on:
      - mongo

  front:
    container_name: front
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/client/src
      - ./public:/app/client/public
    environment:
      - PORT=3000

  mongo:
    image: mongo:3.6
    volumes:
      - db_storage:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017

volumes:
  db_storage:
    driver: local